### PR TITLE
Add pkg/ulimits

### PR DESCRIPTION
**Pull request by dnephin**
`github.com/docker/docker/pkg/ulimits` seems to heavily related to the files in this package. This is a `git subtree` of the package from docker master.

### CODE REVIEW

**Comment by dnephin** [comment]
cc @calavera 

This is what I was suggesting, let me know if you think it fits with this package.

**Comment by calavera** [comment]
I think I'm okay with merging these two package. There are two things we should do before merging this PR:

1. Rename the `Parse` function to something more clear, like `ParseUlimit`.
2. Add example functions like I did in https://github.com/docker/go-units/blob/master/duration_test.go#L9-L41. Those examples are used by godoc.org: https://godoc.org/github.com/docker/go-units#example-BytesSize

**Comment by calavera** [comment]
@dnephin also, please sign your commit. I'm adding the right checks to this repo as soon as this is merged.

**Comment by dnephin** [comment]
Cool, will do.  I didn't know about this godoc feature.

**Comment by dnephin** [comment]
Ok, I've made those changes.  

I made them in a separate commit since the previous commit that I authored is a merge commit.

**Comment by calavera** [comment]
cool thank you. I'm going to merge this and tag master as `v0.2.0`. My PR in docker is still pending to merge, so we might be able to add more changes there and use ulimits from here:
https://github.com/docker/docker/pull/18682#issuecomment-164868363

**Pull request merged**
