### PR TITLE
Removes spaces before unit.

### PR DESCRIPTION
**Pull request by wernight**
This is to be closer to common Linux outputs.
See https://github.com/docker/docker/issues/30271

### CODE REVIEW

**Comment by thaJeztah** [comment]
Could you update the commit message to provide some background for this change (i.e., describe the problem with `sort` without this change)?

also ping @LK4D4 @justincormack PTAL

**Comment by stevvooe** [comment]
LGTM

@thaJeztah Sort breaks because it treats them as separate fields in the comparison.

This may break some tests in docker.

**Comment by thaJeztah** [comment]
> This may break some tests in docker

@stevvooe Yes, tests will have to be updated when this is vendored. Do you think this will be too much of a breaking change?

**Comment by stevvooe** [comment]
@thaJeztah I have no clue how breaking this will be. It really depends on if people parse the byte sizes.

**Comment by wernight** [comment]
I've updated the commit description to include more details.

**Comment by thaJeztah** [comment]
@wernight can you open a PR to docker/docker to update the vendored version? (and the tests?)

**Comment by wernight** [comment]
There is issue https://github.com/docker/docker/issues/30271 there, what would be the PR?

**Comment by thaJeztah** [comment]
The PR would be to update the commit in the vendor file;
https://github.com/docker/docker/blob/master/vendor.conf#L18

Run the `vndr` tool (https://github.com/LK4D4/vndr/blob/master/README.md) to update the dependencies, and update (unit) tests in the docker/docker repository where needed.

Let me know if you want to work on that, or want a maintainer to take care of it.

**Pull request merged**
